toolbox_options=["Symbolic Math Toolbox", 
				"Partial Differential Equation Toolbox",
				"Statistics Toolbox",
				"Curve Fitting Toolbox"
				"Optimization Toolbox",
				"Global Optimization Toolbox",
				"Neural Network Toolbox",
				"Model-Based Calibration Toolbox",
				"Control System Toolbox",
				"System Identification Toolbox",
				"Fuzzy Logic Toolbox",
				"Robust Control Toolbox",
				"Model Predictive Control Toolbox",
				"Aerospace Toolbox",
				"Signal Processing Toolbox",
				"DSP System Toolbox",
				"Communications System Toolbox",
				"Wavelet Toolbox",
				"Fixed-Point Toolbox",
				"RF Toolbox",
				"Phased Array System Toolbox",
				"Image Processing Toolbox",
				"Computer Vision System Toolbox",
				"Image Acquisition Toolbox",
				"OPC Toolbox",
				"Vehicle Network Toolbox",
				"Financial Toolbox",
				"Economics Toolbox",
				"Datafeed Toolbox",
				"Database Toolbox",
				"Spreadsheel Link EX (for Microsoft Excel)",
				"Fixed-income Toolbox",
				"Financial Derivatives Toolbox",
				"Bioinformatics Toolbox",
				"SimBiology"]

matlab_description={"Description": "MATLAB is a programming environment for algorithm development, data analysis, visualization, and numerical computation. Using MATLAB, you can solve technical computing problems faster than with traditional programming languages, such as C, C++, and Fortran.You can use MATLAB in a wide range of applications, including signal and image processing, communications, control design, test and measurement, financial modeling and analysis, and computational biology. For a million engineers and scientists in industry and academia, MATLAB is the language of technical computing.",
					"System Requirements":"Windows: Windows 7 SP1, Vista SP 2, XP SP3, XP x64 Edition SP2, Server 2008 SP2 or R2, Server 2003 R2 SP2. Any Intel or AMD x86 processor supporting SSE2 instruction set. 1 GB for MATLAB only, 3-4 GB for typical installations. At least 1 GB RAM.\n\nLinux: Qualified Distributions: Ubuntu 10.4 LTS, 11.04, 11.10. Red Hat Enterprise Linux 5.x and 6.x. SUSE Linux Enterprise Desktop 11.x. Debian 6.x. Any Intel or AMD x86 processor supporting SSE2 instruction set. 1 GB for MATLAB only, 3-4 GB for a typical installation. At least 1 GB RAM.\n\nMac: Mac OS X 10.7 (Lion) or 10.6.4+ (Snow leopard). All Intel-based Macs with an Intel Core 2 or later. 1 GB for MATLAB only, 3-4 GB for a typical installation. At least 1 GB RAM.",
					"How to Obtain":"Currently available by chart string owner only. Use the request button above to request a copy. Purchasing options are available direct from vendor"}